### ISSUE TITLE
How to get the scribble

### ISSUE THREAD

**Issue by huangyuan2020** [kanezaki/pytorch-unsupervised-segmentation-tip#3]
Thank you very much for your work, I think it is very simple and effective！
Scribble is a very interesting extension module, how did you get the scribble?

**Comment by shiwei-913** [comment]
Have you solved this problem?

**Comment by huangyuan2020** [comment]
> Have you solved this problem?

No,I didn't study this problem now,how about you?

**Comment by shiwei-913** [comment]
I just started researching, unfortunately it has not been resolved yet.

**Comment by Likarian** [comment]
Please see the section 4.B of the paper (arxiv version).  
You can find the mention about the source of scribble information.

**Comment by ghost** [comment]
I solve thie problem.

https://github.com/kanezaki/pytorch-unsupervised-segmentation-tip/issues/5#issuecomment-747513964
